import 'package:flowplanv2/core/ui/app_keys.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('AppKeys expose stable ValueKey names for user workflow controls', () {
    const expected = <String>[
      'flowplan.shell.create_task',
      'flowplan.shell.timeline',
      'flowplan.shell.week',
      'flowplan.shell.month',
      'flowplan.shell.tracker',
      'flowplan.shell.reports',
      'flowplan.shell.files',
      'flowplan.shell.settings',
      'flowplan.quick_add.task_tab',
      'flowplan.quick_add.event_tab',
      'flowplan.task.summary',
      'flowplan.task.save',
      'flowplan.task.complete',
      'flowplan.event.summary',
      'flowplan.event.save',
      'flowplan.tracker.start',
      'flowplan.tracker.review_confirm',
      'flowplan.tracker.input_history.previous_page',
      'flowplan.tracker.input_history.next_page',
      'flowplan.tracker.log_history.previous_page',
      'flowplan.tracker.log_history.next_page',
      'flowplan.report.generate',
      'flowplan.file.transfer_start',
      'flowplan.sync.run',
      'flowplan.settings.save',
      'flowplan.ai_chat.clear',
      'flowplan.web_shell.today',
      'flowplan.web_shell.events',
      'flowplan.web_shell.tasks',
      'flowplan.web_shell.drive',
      'flowplan.web_shell.tracking',
      'flowplan.web_shell.reports',
      'flowplan.web_shell.settings',
      'flowplan.web_shell.refresh_connection',
      'flowplan.web.tasks.create',
      'flowplan.web.tasks.refresh',
    ];

    expect(
      [
        AppKeys.shellCreateTask,
        AppKeys.shellTimeline,
        AppKeys.shellWeek,
        AppKeys.shellMonth,
        AppKeys.shellTracker,
        AppKeys.shellReports,
        AppKeys.shellFiles,
        AppKeys.shellSettings,
        AppKeys.quickAddTaskTab,
        AppKeys.quickAddEventTab,
        AppKeys.taskSummaryField,
        AppKeys.taskSaveButton,
        AppKeys.taskCompleteButton,
        AppKeys.eventSummaryField,
        AppKeys.eventSaveButton,
        AppKeys.trackerStartButton,
        AppKeys.trackerReviewConfirmButton,
        AppKeys.trackerInputHistoryPreviousPageButton,
        AppKeys.trackerInputHistoryNextPageButton,
        AppKeys.trackerLogHistoryPreviousPageButton,
        AppKeys.trackerLogHistoryNextPageButton,
        AppKeys.reportGenerateButton,
        AppKeys.fileTransferStartButton,
        AppKeys.syncRunButton,
        AppKeys.settingsSaveButton,
        AppKeys.aiChatClearButton,
        AppKeys.webShellToday,
        AppKeys.webShellEvents,
        AppKeys.webShellTasks,
        AppKeys.webShellDrive,
        AppKeys.webShellTracking,
        AppKeys.webShellReports,
        AppKeys.webShellSettings,
        AppKeys.webShellRefreshConnection,
        AppKeys.webTasksCreateButton,
        AppKeys.webTasksRefreshButton,
      ].map((key) => (key as ValueKey<String>).value).toList(),
      expected,
    );
  });
}
